import topSet from './images/sushi_1.jpg';
import salmonSet from './images/Sushi_2.jpg'
import margarita from './images/pizza-1.jpeg';
import pepperoni from './images/pizza-2.jpg'


export const mockData = [
    {
        id: '1',
        name: 'Top Set',
        img: topSet,
        category: 'Sets',
        weight: 1020,
        quantity: 40,
        price: 280,
    },
    {
        id: '2',
        name: 'Salmon Combo',
        img: salmonSet,
        category: 'Sets',
        weight: 1050,
        quantity: 30,
        price: 320,
    },
    {
        id: '3',
        name: 'Top Set',
        img: topSet,
        category: 'Sets',
        weight: 1020,
        quantity: 40,
        price: 280,
    },
    {
        id: '4',
        name: 'Salmon Combo',
        img: salmonSet,
        category: 'Sets',
        weight: 1050,
        quantity: 30,
        price: 320,
    },

    {
        id: '5',
        name: 'Top Set',
        img: topSet,
        category: 'Sets',
        weight: 1020,
        quantity: 40,
        price: 280,
    },

    {
        id: '6',
        name: 'Salmon Combo',
        img: salmonSet,
        category: 'Sets',
        weight: 1050,
        quantity: 30,
        price: 320,
    },
    // {
    //     id: '7',
    //     name: 'Margarita',
    //     img: margarita,
    //     category: 'Pizza',
    //     weight: 700,
    //     quantity: 1,
    //     price: 69,
    // },
    // {
    //     id: '8',
    //     name: 'Pepperoni',
    //     img: pepperoni,
    //     category: 'Pizza',
    //     weight: 700,
    //     quantity: 1,
    //     price: 75,
    // },
    // {
    //     id: '9',
    //     name: 'Margarita',
    //     img: margarita,
    //     category: 'Pizza',
    //     weight: 700,
    //     quantity: 1,
    //     price: 69,
    // },
    // {
    //     id: '10',
    //     name: 'Pepperoni',
    //     img: pepperoni,
    //     category: 'Pizza',
    //     weight: 700,
    //     quantity: 1,
    //     price: 75,
    // },
    // {
    //     id: '11',
    //     name: 'Margarita',
    //     img: margarita,
    //     category: 'Pizza',
    //     weight: 700,
    //     quantity: 1,
    //     price: 69,
    // },
    // {
    //     id: '12',
    //     name: 'Pepperoni',
    //     img: pepperoni,
    //     category: 'Pizza',
    //     weight: 700,
    //     quantity: 1,
    //     price: 75,
    // },
]